#!/usr/bin/env bash

# Redirect all calls to `node` to the instrumented version of Node.
# USING ASYNC HOOKS!!!

# INVARIANT: this script expects the following environment variables to be
#            set:
#            - $ASYNC_HOOKS_ANALYSIS_PATH --> path to async hooks analysis to be used.
#                                             this analysis must instrument the
#                                             script given as its argument.

# Get directory of THIS script. This will be used to execute
# the `check-env-vars` script, which should be located in
# the same directory as this script.
SCRIPT_DIRECTORY="$(dirname ${BASH_SOURCE[0]})"

# ensure environment variables are set
$SCRIPT_DIRECTORY/check-env-vars

echo 'Intercepted invocation of `node`! Instrumenting call...'

# instrument execution
# (call node binary directly so we won't recursively call this same script)
/usr/bin/node $ASYNC_HOOKS_ANALYSIS_PATH $@
